Ferremas/Ferremas/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ferremas/app/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', views.inicio),
    path('inicio', views.inicio, name='inicio'),

    # Login
    path('login_registro', views.login_registro, name='login_registro'),
    path("logout/", views.logout_view, name="logout"),
    
    # Agregar producto (solo para administradores)
    path('agregar_producto/', views.agregar_producto, name='agregar_producto'),
    path('load-subcategorias/', views.load_subcategorias, name='load_subcategorias'),

    # Lista de productos
    path('productos/', views.lista_productos, name='lista_productos'),


   # Carrito
    path('carrito/', views.ver_carrito, name='ver_carrito'),
    path('comprar-producto/', views.comprar_producto, name='comprar_producto'),
    path('sumar-producto/', views.sumar_producto, name='sumar_producto'),
    path('restar-producto/', views.restar_producto, name='restar_producto'),


    # mercadopago
    path("process_payment/", views.process_payment, name="process_payment"),
    path("crear_preferencia/", views.crear_preferencia, name="crear_preferencia"),

    # Confirmación de pago exitoso
    path('pago_exitoso/', views.pago_exitoso, name='pago_exitoso'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ferremas/app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Categoria(models.Model):
    id_categoria = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50)

    def __str__(self):
        txt = "Categoria: {0} "
        return txt.format(self.nombre)
    
class Subcategoria(models.Model):
    id_subcategoria = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50)
    categoria = models.ForeignKey(Categoria, related_name='subcategorias', on_delete=models.CASCADE)

    def __str__(self):
        txt = "{0} - Subcategoría: {1}"
        return txt.format(self.categoria, self.nombre)
    
class User(AbstractUser):
    NIVELES_USUARIO = [
        ('admin', 'Administrador'),
        ('cliente', 'Cliente')
    ]
    
    nombre = models.CharField(max_length=50, null=False)
    apellido = models.CharField(max_length=50, null=False)
    email = models.EmailField(max_length=50, null=False, unique=True)
    password = models.CharField(max_length=100, null=False)
    telefono = models.CharField(max_length=12, null=False)
    direccion = models.CharField(max_length=100, null=False)
    nivel = models.CharField(max_length=10, choices=NIVELES_USUARIO, default='cliente')
    
    def __str__(self):
        txt = "{0} - [{1}]"
        return txt.format(self.username, self.nivel )

class Producto(models.Model):
    sku = models.IntegerField(primary_key=True)
    precio = models.IntegerField()
    stock = models.IntegerField()
    nombre = models.CharField(max_length=80)
    descripcion = models.TextField()
    imagen = models.ImageField(upload_to="imagenesProducto")
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    subcategoria = models.ForeignKey(Subcategoria, on_delete=models.CASCADE)
    fecha_ingreso = models.DateField(auto_now_add=True)
    disponible = models.BooleanField(default=True)

    def decrementar_stock(self, cantidad):
        if self.stock >= cantidad:
            self.stock -= cantidad
            if (self.stock == 0):
                self.disponible = False
            self.save()
        else:
            raise ValueError("No hay suficiente stock para decrementar.")

    def __str__(self):
        txt = "Sku: {0} | Nombre: {1} | Stock: {2} | Precio: {3} | Disponible: {4}"
        return txt.format( self.sku, self.nombre , self.stock, self.precio, self.disponible)

class Order(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE
    )  # Usuario que hizo el pedido
    total_amount = models.DecimalField(max_digits=10, decimal_places=0)
    created_at = models.DateTimeField(auto_now_add=True)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="items")
    product = models.ForeignKey(Producto, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=0)
    image = models.ImageField(
        upload_to="imgOrden", null=True, blank=True
    )  # Allow null and blank

    def save(self, *args, **kwargs):
        if not self.id:  # Only copy the image when creating a new OrderItem
            self.image = self.product.imagen
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.quantity} x {self.product.nombre} - {self.order}"




class Carrito(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.usuario.username} - {self.producto.nombre} - {self.cantidad}"

Ferremas/app/templates/agregar_producto.html
{% extends "base.html" %}

{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/agregar_producto.css' %}">
{% endblock %}

{% block body %}
  <div class="container mt-5">
    <h2>Agregar Producto</h2>
    <form method="post" enctype="multipart/form-data" id="productoForm">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Agregar Producto</button>
    </form>
  </div>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script type="text/javascript">
    $(document).ready(function () {
      $('#id_categoria').change(function () {
        var url = "{% url 'load_subcategorias' %}";  // Obtener la URL desde las URL patterns
        var categoriaId = $(this).val();

        $.ajax({
          url: url,
          data: {
            'categoria_id': categoriaId
          },
          success: function (data) {
            $('#id_subcategoria').html('');  // Limpiar el campo de subcategoría
            $.each(data, function (key, value) {
              $('#id_subcategoria').append('<option value="' + value.id_subcategoria + '">' + value.nombre + '</option>');
            });
          }
        });
      });

      // Ajuste automático del textarea de descripción
      $('#id_descripcion').on('input', function () {
        this.style.height = 'auto';
        this.style.height = (this.scrollHeight) + 'px';
      });

      // Inicializar el tamaño del textarea de descripción en carga
      $('#id_descripcion').each(function () {
        this.style.height = 'auto';
        this.style.height = (this.scrollHeight) + 'px';
      });
    });
  </script>
{% endblock %}

Ferremas/app/templates/base.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/styleNavbar.css'%}">
    <link rel="icon" href="{% static 'img/logo-sin-fondo.png' %}">
    {% block head %}
    {% endblock %}
</head>
<body>
    
    <!-- Inicio Navbar lateral -->
    <nav class="sidebar close">
        <header>
            <div class="image-text">
                <span class="image">
                    <img id="plant" src="{% static 'img/logo-sin-fondo.png' %}" alt="">
                </span>

                <div class="text logo-text ms-3">
                    <span class="name"></span>
                    <span class="profession">Ferremas</span>
                </div>
            </div>

            <i class="bi bi-chevron-right toggle"></i>
        </header>

        <div class="menu-bar">
            <div class="menu">
                <div class="contenedorReloj">
                    <h1 class="text" id="hora"><strong>00:00:00 <p id="AMPM" class="text"></p></strong></h1>
                    <p class="text" id="fecha">fecha</p>
                </div>

                <li class="search-box">
                    <i id="icon" class="bi bi-search"></i>
                    <input type="text" placeholder="Buscar...">
                </li>

                <li class="nav-link">
                  <a href="http://186.64.123.144">
                      <i id="icon" class="bi bi-megaphone"></i>
                      <span class="text nav-text">Spart Sagan</span>
                  </a>
                </li>

                <li class="nav-link">
                    <a class="" href="/inicio">
                        <i id="icon" class="bi bi-house-door"></i>
                        <span class="text nav-text">Inicio</span>
                    </a>
                </li>

                <li class="nav-link">
                    <a href="#">
                        <i id="icon" class="bi bi-info-circle"></i>
                        <span class="text nav-text">Nosotros</span>
                    </a>
                </li>

                <li id="nav-link">
                    <a href="{% url 'lista_productos' %}">
                        <i id="icon" class="bi bi-box-seam"></i>
                        <span class="text nav-text">Productos</span>
                    </a>
                </li>

                {% if user.is_authenticated and user.nivel == 'admin' %}
                <li class="nav-link">
                    <a href="{% url 'agregar_producto' %}">
                        <i id="icon" class="bi bi-plus-circle"></i>
                        <span class="text nav-text">Agregar Producto</span>
                    </a>
                </li>
                {% endif %}

            </div>
            

            <div class="bottom-content">
                   
                <li id="logout" class="nav-item dropdown">
                    {% if user.is_authenticated %}
                            <a class="nav-link dropdown- btn btn-outline-dark" id="TextNavbarIcons" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false"><i id="icon" class="bi bi-person"></i>{{user.username}}</a>
                            {% else %}  
                            
                                <a href="{% url 'login_registro' %}"><i id="icon" class="bi bi-person"></i><span class="text nav-text">Iniciar Sesión</span></a>
                            {% endif %}
                    <ul id="dropNavbar" class="text dropdown-menu" style="background-color: var(--body-color);">
                        <form method="post" action="{% url 'logout' %}">
                            {% csrf_token %}
                            <li><button class="dropdown-item" type="submit" name="logout">Cerrar sesion</button></li>
                        </form>
                    </ul>
                </li>

                <li class="mode">
                    <div class="sun-moon">
                        <i id="icon_luna" class="bi bi-moon"></i>
                        <i id="icon_sol" class="bi bi-brightness-high"></i>
                    </div>
                    <span class="mode-text text">Modo oscuro</span>

                    <div class="toggle-switch">
                        <span class="switch"></span>
                    </div>
                </li>

            </div>
        </div>
    </nav>
    <!-- Fin Navbar lateral -->
    <section class="home">
        {% block body %}
        {% endblock %}
        <footer>
          <div class="container-fluid">
              <div class="row p-5 pb-2 bg-dark text-white">
                <div class="col-xs-12 col-md-6 col-lg-3">
                  <p class="h2">SweetGarden</p>
                  <p class="text-secondary text-decoration-none">Santiago, Chile</p>
                </div>
                <div class="col-xs-12 col-md-6 col-lg-3">
                  <p class="h5 mb-3">Mas recursos</p>
                  <div class="mb-2">
                    <a class="text-secondary text-decoration-none" href="#">homevan</a>
                  </div>
                  <div class="mb-2">
                    <a class="text-secondary text-decoration-none" href="#"
                      >jhpaisajismo</a>
                  </div>
                  <div class="mb-2">
                    <a class="text-secondary text-decoration-none" href="#"
                      >cultigarden</a>
                  </div>
                </div>
                <div class="col-xs-12 col-md-6 col-lg-3">
                  <p class="h5 mb-3">Links</p>
                  <div class="mb-2">
                    <a class="text-secondary text-decoration-none" href="#"
                      >Terminos & condiciones</a>
                  </div>
                  <div class="mb-2">
                    <a class="text-secondary text-decoration-none" href="#">Politica</a>
                  </div>
                </div>
                <div class="col-xs-12 col-md-6 col-lg-3">
                  <p class="h5 mb-3">Contacto</p>
                  <div class="mb-2">
                    <a class="text-secondary text-decoration-none" href="#"
                      >Instagram</a>
                  </div>
                  <div class="mb-2">
                    <a class="text-secondary text-decoration-none" href="#">Whatsapp</a>
                  </div>
                </div>
                <div class="col-xs-12 pt-4">
                  <p class="text-white text-center pt-5 ">Copyright - Todos los derechos resevados © 2023 </p>
                </div>
              </div>
            </div>
        </footer>
    </section>
</body>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js"
  integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js"
  integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
<script src="{% static 'js/navbar.js'%}"></script>
<script src="{% static 'js/reloj.js'%}"></script>
{% block script %}
{% endblock %}

Ferremas/app/templates/compras.html
{% extends "base.html" %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/compras.css' %}">
<script src="https://sdk.mercadopago.com/js/v2">
</script>
<title>Compras</title>
{% endblock %}

{% block body %}
<!-- Inicio Carrito -->

{% if total < 1 %}
    <div class="container">
        <h3>No tienes nada en tu carro</h3>
        <h4>Ve a la tienda para agregar cosas a tu carro</h4>
        <a href="{% url 'lista_productos' %}">
            <button id="carritoBoton" class="carrito-boton">
                <i class="bi bi-cart"></i>
                <span id="cantidadCarrito">0</span>
            </button>
        </a>
    </div>
{% else %}
    <div class="cart-container">
        
        <div class="cart-item">
             {% for item in productos_usuario %}
            <div class="item" data-sku="{{ item.producto.sku }}"
                                data-nombre="{{ item.producto.nombre }}"
                                data-cantidad="{{ item.cantidad }}"
                                data-precio="{{ item.producto.precio }}"
                                data-imagen="{{ item.producto.imagen.url }}">
                <img src="{{ item.producto.imagen.url }}" alt="">
                <div class="cart-item-details" style="width: 100%; display: flex; flex-direction: column; justify-content: center;">
                    <h3>{{ item.producto.nombre }}</h3>

                    <div class="quantity-control">
                        <button class="btn-resta" data-sku="{{ item.producto.sku }}">-</button>
                        <span class="cantidad">{{ item.cantidad }}</span>
                        <button class="btn-suma" data-sku="{{ item.producto.sku }}">+</button>
                    </div>
                </div>
                <div class="precio"><span><strong>{{ item.producto.precio }}</strong> CLP</span></div>
            </div>
            {% endfor %}
        </div>
        <div class="cart-summary">
            <h3>Resumen</h3>
            {% if total == 1 %}
                <p>{{ total }} producto</p>
            {% else %}
                <p>{{ total }} productos</p>
            {% endif %}
            <h4 class="total" data-total="{{ total_precio }}">Total: <span id="total_precio">{{ total_precio }} CLP</span></h4>
        </div>
        
    </div>
    <div id="paymentBrick_container"></div>
{% endif %}


{% endblock %}

{% block script %}
<script src="{% static "js/mercadopago.js" %}"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(document).ready(function() {
    $('.btn-suma').on('click', function() {
        var sku = $(this).data('sku');

        $.ajax({
            url: "{% url 'sumar_producto' %}",
            type: 'POST',
            data: {
                'sku': sku,
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            success: function(response) {
                if (response.status === 'success') {
                    var item = $('.item[data-sku="' + sku + '"]');
                    var cantidadSpan = item.find('.cantidad');
                    cantidadSpan.text(parseInt(cantidadSpan.text()) + 1);
                    $('#total_precio').text(response.total_precio + ' CLP');
                }
            }
        });
    });

    $('.btn-resta').on('click', function() {
        var sku = $(this).data('sku');

        $.ajax({
            url: "{% url 'restar_producto' %}",
            type: 'POST',
            data: {
                'sku': sku,
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            success: function(response) {
                if (response.status === 'success') {
                    var item = $('.item[data-sku="' + sku + '"]');
                    var cantidadSpan = item.find('.cantidad');
                    var nuevaCantidad = parseInt(cantidadSpan.text()) - 1;
                    if (nuevaCantidad > 0) {
                        cantidadSpan.text(nuevaCantidad);
                    } else {
                        item.remove();
                    }
                    $('#total_precio').text(response.total_precio + ' CLP');
                }
            }
        });
    });
});
</script>
{% endblock %}

Ferremas/app/templates/inicio.html
{% extends "base.html" %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/inicio.css' %}">
<title>Inicio</title>
<style>
  .modal {
      display: none;
      align-items: center;
      justify-content: center;
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background-color: rgba(0, 0, 0, 0.5);
      z-index: 200; /* Asegura que el modal esté por encima del sidebar */
  }
  .modal-content {
      background-color: var(--sidebar-color);
      padding: 20px;
      border-radius: 5px;
      text-align: center;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
      color: var(--text-color);
      width: 300px; /* Ancho del recuadro pequeño */
  }
  .modal-buttons {
      margin-top: 20px;
  }
  .modal-buttons button {
      padding: 10px 20px;
      margin: 0 10px;
      border: none;
      border-radius: 5px;
      cursor: pointer;
  }
  .btn-confirm {
      background-color: #4CAF50;
      color: white;
  }
  .btn-cancel {
      background-color: #f44336;
      color: white;
  }
</style>
{% endblock %}

{% block body %}
<body>
    <!-- Inicio Tienda -->
      
  
    <section class="w-50 mx-auto text-center pt-5" id="intro">
      <h1 style="color: rgba(139,31,46,255)">Ferremas</h1>
      <h1 class="p-3 fs-2 border-top border-2">
        ¡Bienvenidos a nuestra página de
        <span style="color: rgba(139,31,46,255)">Construccion y Seguridad</span>
      </h1>
      <p class="p-3 fs-6">
        En <span style="color: rgba(139,31,46,255)">Ferremas</span> Aquí encontrarás todo lo que necesitas saber para adquirir y utilizar productos de construcción y seguridad en tus proyectos. La construcción
         es una actividad que puede ser muy gratificante y esencial para crear espacios funcionales y seguros, además de ser una excelente manera de mejorar y proteger tu entorno.
      </p>
    </section>
  
    <!-- informacion extra -->
    <div class="container-fluid text-center">
      <div class="row">
        <div class="col mt-4 pt-5 pb-5">
          <i class="fa-solid fa-book display-5 pb-3"></i>
          <h3 style="color: rgba(139,31,46,255)" >Desarrollo Avanzado</h3>
          <p>
            Productos de alta calidad, ampliamente utilizados y validados en
           la industria.
          </p>
        </div>
  
        <div class="col mt-4 pt-5 pb-5">
          <i class="fa-solid fa-leaf display-5 pb-3"></i>
          <h3 style="color: rgba(139,31,46,255)" >Productos indispensables</h3>
          <p>
            Sin desgaste prematuro, corrosión, deformación y fallos estructurales que puedan comprometer la seguridad y la calidad de tus proyectos de construcción.
          </p>
        </div>
        <div class="col mt-4 pt-5 pb-5">
          <i class="fa-solid fa-globe display-5 pb-3"></i>
          <h3 style="color: rgba(139,31,46,255)" >Para todo el uso</h3>
          <p>
           
Productos para las áreas de construcción, remodelación, proyectos de infraestructura, incluso proyectos personales de mejoras en el hogar.
          </p>
        </div>
      </div>
    </div>
  
    <div class="container">
      
  
      <span class="info-Quehacemo">
        
        <h1 style="color: rgba(139,31,46,255)" >Vendemos los mejores productos de construcción y ferretería</h1>
        <br/>
        <p>
          Nuestra página se especializa en la venta de productos de la mejor calidad con el principal objetivo de asegurar la durabilidad y seguridad de tus proyectos. Además, ofrecemos una amplia gama de herramientas, materiales y suministros para ayudarte en todas tus necesidades de construcción y remodelación.
        </p>
        <ul>
          <li>Productos seleccionados</li>
          <br />
          <li>Formatos convenientes</li>
          <br />
          <li>catalogo actualizado</li>
        </ul>
        <div class="boton1 ps-3 pt-2 pb-4">
          <a href="/productos#maceteros">
          <button class="btn btn-success">Productos</button></a>
        </div>
      </span>
    </div>
  
   
    
    <div class="container-fluid text-center" >
      <div class="row">
        <div class="col mt-4 pt-5 pb-5">
          <h1 style="rgba(139,31,46,255)">Ubicado en Santiago, Chile</h1>
        <br />
        <p>
          Elegimos Santiago para nuestra sucursal con el objetivo de estar cerca de nuestros clientes, estamos ubicados Macul, cerca de los mejores restaurantes, tiendas y parques, y tan solo a 15 minutos de una espectacular piscina. ¡Visitenos y no se arrepentiran!
        </p>
        <p>nos puedes contactar o encontrar tambien!</p>
        <p>llamanos al: +56 9289 9192</p>
        
        <div id="Clima">
          <h4 id="resultDolar">Clima: </h4>
          <h4 id="resultDolar2">Descripción: </h4>
          <h4 id="resultDolar3"> La temperatura es: </h4>
          <h4 id="resultDolar4"></h4>
          <h4 id="resultDolar5"></h4>
          <h4 id="resultDolar6"></h4>
          <h4 id="resultDolar7"></h4>
      </div>
        </div>
  
        <div class="col pb-2 " id="mapa">
          
           <iframe
          src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d53262.28925476311!2d-70.6935409844393!3d-33.45209207784555!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9662d0069af23abb%3A0x879d59f409ed4897!2sSantiago%2C%20Regi%C3%B3n%20Metropolitana!5e0!3m2!1ses!2scl!4v1680408793706!5m2!1ses!2scl"
          style="border: 0; width: 100%; height: 100%;"
          allowfullscreen=""
          loading="lazy"
          referrerpolicy="no-referrer-when-downgrade"
        ></iframe> 
        
        </div>
      </div>
    </div>
   

    
    <div class="modal" id="announcement">
      <div class="modal-content">
          <p>¿Deseas comer unas ricas hamburguesas? Podrás econtrarlo en la página Spart Sagan</p>
          <div class="modal-buttons">
              <button class="btn-confirm" onclick="redirect()">Sí</button>
              <button class="btn-cancel" onclick="closeModal()">Cancelar</button>
          </div>
      </div>
  </div>

  </body>
  <!-- Fin Tienda --> 
{% endblock %}

{% block script %}
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
<script src="{% static 'js/Clima.js' %}"></script>
<script>
  window.onload = function() {
      document.getElementById('announcement').style.display = 'flex';
  };

  function redirect() {
      window.location.href = "http://186.64.123.144";
  }

  function closeModal() {
      document.getElementById('announcement').style.display = 'none';
  }
</script>

{% endblock %}

Ferremas/app/templates/pago_exitoso.html
{% extends "base.html" %}

{% load static %}
{% load multiply %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/pago_exitoso.css' %}">
<title>Pago Exitoso</title>
{% endblock %}

{% block body %}
<div class="boleta-container">
    <h1>¡Pago Exitoso!</h1>
    <h2>Boleta de Compra</h2>
    <p><strong>Usuario:</strong> {{ usuario.username }}</p>
    <p><strong>Correo Electrónico:</strong> {{ usuario.email }}</p>
    <p><strong>Fecha:</strong> {{ ahora }}</p>
    <table class="boleta-table">
        <thead>
            <tr>
                <th>Producto</th>
                <th>Cantidad</th>
                <th>Precio Unitario</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            {% for item in carrito %}
            <tr>
                <td>{{ item.producto.nombre }}</td>
                <td>{{ item.cantidad }}</td>
                <td>{{ item.producto.precio }} CLP</td>
                <td>{{ item.producto.precio|multiply:item.cantidad }} CLP</td>
            </tr>
            {% endfor %}
            <tr>
                <td colspan="3"><strong>Total</strong></td>
                <td><strong>{{ total_precio }} CLP</strong></td>
            </tr>
        </tbody>
    </table>
</div>
{% endblock %}

{% block script %}
<script>
    // Aquí puedes agregar cualquier script necesario
</script>
{% endblock %}

<style>
.boleta-container {
    width: 80%;
    margin: 0 auto;
    text-align: center;
    padding: 20px;
    background: #f9f9f9;
    border-radius: 8px;
    box-shadow: 0 0 10px rgba(0,0,0,0.1);
}

.boleta-table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 20px;
}

.boleta-table th, .boleta-table td {
    border: 1px solid #ddd;
    padding: 8px;
    text-align: left;
}

.boleta-table th {
    background-color: #f2f2f2;
}

.boleta-table td {
    background-color: #fff;
}
</style>